#!/bin/sh

red="\033[1;31m"
c1="\033[47m\033[34m"

make_copy_or_restore() 
{
	name="$1"
	copyname="$1.gl-virt-copy"
	if [ -e "$copyname" ]; then
		echo "${red}previously copy of $name found in $copyname, restored${c1}"
		cp -f $copyname $name
	else
		echo "${red}making backup copy of $name in $copyname${c1}"
		cp $name $copyname
	fi
}

if_exist_remove()
{
	if [ -e $1 ] || [ -d $1 ]; then
		echo "${red}odd ? previously installation detected: $1 removed${c1}"
		rm -rf $1
	fi
}

check_required_file() 
{
	if [ -e "$1" ]; then
		echo "${red}checked File $1: exist${c1}"
	else
		echo "${red}File $1 not exist! $2 ${c1}"
		ls -lr /home/globaleaks/HS
		exit
	fi
}

boxname=`hostname`

echo "This script will setup this box $boxname, install GlobaLeaks, potentially damage data"
echo "This script has been tester only in the Ubuntu Server 11.10 VirtualBox"
echo "If you're starting this script in a different environment, effects are unpredictable"
echo "maybe you don't want run this shell script, you can download the VirtualBox image already setup"
echo "check in the Readme.md for more info"
echo "^c to quit, ENTER to continue"
read x

echo "Checking privileges, am I root ?"
if [[ $UID != "0" ]]
then
	echo "${red}I'm not root, use sudo -s (default password: reverse)${c1}"
	exit
else
	echo "${red}Ok, I'm root, installation possible ${c1}"
fi

echo "${red}fixing network defaults"
dhclient eth2
route add default gw 172.16.254.1

echo "${red}Checking network connection, using http://www.globaleaks.org as test${c1}"
cd /tmp
rm -rf index.html
wget http://www.globaleaks.org
check_required_file "/tmp/index.html" "network not connected"

cd /root
echo "${red}Installing python-pip and Tor${c1}"
aptitude install python-pip tor

echo "${red}Installing web2py${c1}"
pip install web2py

echo "${red}adding globaleaks user and group${c1} and /home/globaleaks base directory for installation"
groupadd globaleaks
adduser --ingroup globaleaks --disabled-login --quiet --system globaleaks

echo "${red}cloning GlobaLeaks repository (not the default GL, but the VirtualBox modified package)${c1}"
cd /home/globaleaks
if_exist_remove "/home/globaleaks/GlobaLeaks"
git clone http://github.com/globaleaks/GlobaLeaks.git

echo "${red}Creating Tor hidden service..${c1}"
if_exist_remove "/home/globaleaks/HS"
mkdir /home/globaleaks/HS
chown debian-tor.debian-tor /home/globaleaks/HS

TORRC="/etc/tor/torrc"
make_copy_or_restore $TORRC
echo "HiddenServiceDir /home/globaleaks/HS" >> $TORRC
echo "HiddenServicePort 10000 127.0.0.1:8000" >> $TORRC
/etc/init.d/tor restart
sleep 1

check_required_file "/home/globaleaks/HS/hostname" "unable to setup the Tor hidden service!"
hiddenservice=`cat /home/globaleaks/HS/hostname` 
echo "${red}started hidden service with name $hiddenservice pointing to 127.0.0.1:8000${c1}"

echo "${red}Tor is already in the init script, setting startup for globaleaks service${c1}"
cd /home/globaleaks/GlobaLeaks/
echo "${red}working in `pwd` ${c1}"

INIS="/etc/init.d/globaleaks"
SOURCE="/home/globaleaks/GlobaLeaks/globaleaks/scripts/globaleaks.debian.init.sh"
if_exist_remove $INIS
echo "# script generated by github source + virtual init setup" > $INIS
echo "#!/bin/sh" >> $INIS
echo 'ADDRESS="172.16.254.2"' >> $INIS
echo 'DAEMON_DIR=/home/globaleaks/GlobaLeaks/globaleaks' >> $INIS
cat $SOURCE | grep -v "^#" | grep -v "ADDRESS=" | grep -v "DAEMON_DIR=" | grep -v linux-firewall >> $INIS
chmod +x $INIS

