#!/bin/sh

red="\033[1;31m"
c1="\033[47m\033[34m"

make_copy_or_restore() 
{
	name="$1"
	copyname="$1.gl-virt-copy"
	if [ -e "$copyname" ]; then
		echo "${red}previously copy of $name found in $copyname, restored${c1}"
		cp -f $copyname $name
	else
		echo "${red}making backup copy of $name in $copyname${c1}"
		cp $name $copyname
	fi
}

if_exist_remove()
{
	if [ -e $1 ] || [ -d $1 ]; then
		echo "${red}odd ? previously installation detected: $1 removed${c1}"
		rm -rf $1
	fi
}

check_required_file() 
{
	if [ ! -e "$1" ]; then
		echo "${red}File $1 not exist! $2 ${c1}"
		exit
	fi
}

boxname=`hostname`

echo "This script will setup this box $boxname, install GlobaLeaks, potentially damage data"
echo "This script has been tester only in the Ubuntu Server 11.10 VirtualBox"
echo "If you're starting this script in a different environment, effects are unpredictable"
echo "This script modify your network settings, and expect that in the host box, where VirtualBox run"
echo "You're following the configuration here explain: https://github.com/vecna/GL-virtual"
echo "\n"
echo "maybe you don't want run this shell script, you can download the VirtualBox image already setup"
echo "^c to Quit, ENTER to continue..."
read x

echo "Checking privileges, am I root ?"
if [ $UID != 0 ]; then
	echo "${red}I'm not root, use sudo -s (default password: reverse)${c1}";
	exit;
else
	echo "${red}Ok, I'm root, installation possible ${c1}"
fi

IFACEFILE="/etc/network/interfaces"
echo "${red}writing network defaults in $IFACEFILE${c1}"
make_copy_or_restore $IFACEFILE 
echo "auto lo" > $IFACEFILE
echo "iface lo inet loopback" >> $IFACEFILE
echo "auto eth2" >> $IFACEFILE
echo "iface eth2 inet static" >> $IFACEFILE
echo "address 172.16.254.2" >> $IFACEFILE
echo "network 172.16.254.0" >> $IFACEFILE
echo "netmask 255.255.255.0" >> $IFACEFILE
echo "broadcast 172.16.254.255" >> $IFACEFILE
echo "gateway 172.16.254.1" >> $IFACEFILE

echo "${red}writing network defaults in $IFACEFILE and restart eth2 interface ${c1}"
ifdown eth2
ifup eth2

echo "${red}Modify /etc/hosts (hostbox and globalx-vm) ${c1}"
make_copy_or_restore "/etc/hosts"
echo "172.16.254.1 hostbox " >> /etc/hosts
echo "172.16.254.2 globalx-vm " >> /etc/hosts

RESOLVCFG="/etc/resolv.conf"
make_copy_or_restore $RESOLVCFG
echo "${red}Configuring $RESOLVCFG ${c1}"
echo "nameserver 194.20.8.4" > $RESOLVCFG
echo "nameserver 213.92.5.54" >> $RESOLVCFG


echo "${red}Checking network connection, using http://www.globaleaks.org as test${c1}"
cd /tmp
rm -rf index.html
wget --timeout=2 http://www.globaleaks.org
check_required_file "/tmp/index.html" "network not connected: maybe your hostbox is not correctly a gateway ?"

cd /root
echo "${red}Installing python-pip and Tor${c1}"
aptitude install python-pip tor

echo "${red}Installing web2py${c1}"
pip install web2py

echo "${red}adding globaleaks user and group, and /home/globaleaks base directory for installation${c1}"
groupadd globaleaks
adduser --ingroup globaleaks --disabled-login --quiet --system globaleaks

echo "${red}cloning GlobaLeaks repository${c1}"
cd /home/globaleaks
if_exist_remove "/home/globaleaks/GlobaLeaks"
git clone http://github.com/globaleaks/GlobaLeaks.git

echo "${red}Creating Tor hidden service..${c1}"
if_exist_remove "/home/globaleaks/HS"
mkdir /home/globaleaks/HS
chown debian-tor.debian-tor /home/globaleaks/HS

TORRC="/etc/tor/torrc"
make_copy_or_restore $TORRC
echo "HiddenServiceDir /home/globaleaks/HS" >> $TORRC
echo "HiddenServicePort 10000 127.0.0.1:8000" >> $TORRC
/etc/init.d/tor restart
sleep 1

check_required_file "/home/globaleaks/HS/hostname" "unable to setup the Tor hidden service!"
hiddenservice=`cat /home/globaleaks/HS/hostname` 
echo "${red}started hidden service with name $hiddenservice pointing to 127.0.0.1:8000${c1}"

cd /home/globaleaks/GlobaLeaks/
echo "${red}fixing privileges in /home/globaleaks files${c1}"
chown -R globaleaks.globaleaks .

INIS="/etc/init.d/globaleaks"
SOURCE="/home/globaleaks/GlobaLeaks/globaleaks/scripts/globaleaks.debian.init.sh"
if_exist_remove $INIS
check_required_file $SOURCE "not found in repository the required script!"
echo "# script generated by github source + virtual init setup" > $INIS
echo "#!/bin/sh" >> $INIS
echo 'ADDRESS="172.16.254.2"' >> $INIS
echo 'DAEMON_DIR=/home/globaleaks/GlobaLeaks/globaleaks/' >> $INIS
# remind: "firewall" handle linux-firewall.sh and firewall_[start|stop] 
cat $SOURCE | grep -v "^#" | grep -v "ADDRESS=" | grep -v "DAEMON_DIR=" | grep -v torrify_ | grep -v firewall >> $INIS
chmod +x $INIS

echo "${red}Disabling autostart for Tor service (is managed by GlobaLeaks)${c1}"
update-rc.d tor disable
/etc/init.d/tor stop
echo "${red}Enabling GlobaLeaks service autostart${c1}"
update-rc.d globaleaks enable
echo "${red}Starting GlobaLeaks service${c1}"
/etc/init.d/globaleaks start


